### ISSUE TITLE
Save the files before compilation

### ISSUE THREAD

**Issue by robertdxyz** [spark/particle-dev-local-compiler#12]
The files should be automatically saved when pressing the compilation button or at least it should ask you if you would like to do that.

This is an issue with the cloud compilation too.

@suda what do you think?

**Comment by suda** [comment]
Yup, there was a conversation about it here: https://github.com/spark/spark-dev/issues/31
As local compiler uses `spark-dev`'s methods to get project, once this feature is implemented there it should work for both local and cloud compilation.
