### ISSUE TITLE
Use smaller virtual machine disk

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev-local-compiler#13]
The virtual machine disk installed by Docker `~/.docker/machine/machines/default/disk.vmdk` weights almost 22 GB. 22 GB is almost 10% of a 256 GB SSD.

Is there a way to squeeze it to a more acceptable size?

Thank you!

**Comment by suda** [comment]
You can remove versions you don't want using `docker rmi` command. In the future this will be done using #8.

**Comment by rei-vilo** [comment]
@suda
1. Providing a procedure would be appreciated.

List the images with `docker images` and then launch `docker rmi <IMAGE ID>`, with `<IMAGE ID>` provided in the list.
1. This procedure has no impact on the size of the virtual machine, so the answer is not relevant.
2. Please reopen the ticket.

**Comment by rei-vilo** [comment]
Ticket reopened as #16.
