### ISSUE TITLE
Provide native build on Mac OS X

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev-local-compiler#14]
Build is performed on a virtual machine installed by Docker. This requires wastes processing and disk resources.

Any plan to provide native build?

Mac OS X is based on Unix, so there shouldn't be major issues.

Thanks!

**Comment by zsup** [comment]
Just want to :+1: this one. The Docker installer seems nice in theory but with such a heavy system requirement it sort of eliminates the value of a container-based deployment. Perhaps Docker isn't the best solution for a local compiler?

**Comment by rei-vilo** [comment]
Some stats:
- Total downloaded = 6 GB
- Total disk used = 25 GB, mostly by the virtual machine

**Comment by suda** [comment]
When #8 will be implemented, only only latest version will be downloaded (~600MB transfer and 1-2GB disk space) by default. Native version [was considered but isn't a manageable way for us to provide support](https://github.com/spark/spark-dev/issues/27#issuecomment-155741255).

There is [a community effort](https://community.particle.io/t/particle-offline-compiler-atom-package-for-100-local-compiling-auto-dfu-update/14068) to provide native build in Particle Dev though.
