### ISSUE TITLE
Use smaller virtual machine disk — again

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev-local-compiler#16]
@suda

Following #13, the procedure with `docker rmi` has no impact on the size of the virtual machine. Ticket #13 hasn't been reopened, hence this new ticket.

> - Providing a procedure would be appreciated.
> 
> List the images with docker images and then launch `docker rmi <IMAGE ID>`, with `<IMAGE ID>` provided in the list.
> - This procedure has no impact on the size of the virtual machine, so the answer is not relevant.
> - Please reopen the ticket.

**Comment by suda** [comment]
Sorry my comment with instructions apparently got lost by GitHub :/

You can [compact the drive](http://askubuntu.com/a/444599) or recreate VM using:

`docker-machine rm default && docker-machine create default` and then fetching only latest version: `docker pull particle/buildpack-particle-firmware:v0.4.7`
