### ISSUE TITLE
Compiler depends on `latest` tag instead of semver versions

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev-local-compiler#17]
I followed the procedure [After updating firmware versions Docker VM has grown to over 20GB](https://github.com/spark/particle-dev-local-compiler#q-after-updating-firmware-versions-docker-vm-has-grown-to-over-20gb). The VM is now 3 GB.
- Particle Dev displays Photon and v0.4.7 at the bottom of the window. 
- Settings for the Particle Dev Local Compiler are correct.

However, building fails with 

<img width="472" alt="capture 2015-11-23 a 17 34 42" src="https://cloud.githubusercontent.com/assets/951776/11342850/984dd184-9209-11e5-96ce-4aa2281d43dc.png">

but

> $ docker images
> REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
> particle/buildpack-particle-firmware   v0.4.7              e4554a679713        2 weeks ago         2.053 GB

and

> $ ls /Users/ReiVilo/.docker/machine/machines/default
> boot2docker.iso cert.pem    default     id_rsa      key.pem     server.pem
> ca.pem      config.json disk.vmdk   id_rsa.pub  server-key.pem

**Comment by suda** [comment]
What does `docker-machine env` say? Are those values different from previous ones that are in package settings?

**Comment by rei-vilo** [comment]
They are exactly the same as before. I double-checked them and copied-pasted them again from `docker-machine env default` to `Settings`.

**Comment by rei-vilo** [comment]
Selecting `v0.4.7` again and launching a new build against **Photon** succeeded. 

It seems the `latest` container isn't created/installed, hence the need for specifying `v0.4.7` manually.

Now, a new issue with the **Core** board.

Building against **Core** fails with `v0.4.7`. 

<img width="463" alt="capture 2015-11-23 a 17 52 00" src="https://cloud.githubusercontent.com/assets/951776/11343157/f6c13246-920a-11e5-98b3-5463caf52c6f.png">

Could `v0.4.6` be installed alongside with the same procedure? The VM should bump up to 6 GB.

**Comment by suda** [comment]
Thanks for testing it out! Seems like local compiler depends too much on `latest` tag.

0.4.6 should work with the same method.

**Comment by rei-vilo** [comment]
Ok, I confirm, build against **Core** works only with `v0.4.6`, not `v0.4.7`.

VM size is unchanged at 3 GB.

**Comment by suda** [comment]
👍
