### ISSUE TITLE
Better Compiler Errors (Similar to Build IDE)

### ISSUE THREAD

**Issue by chobberoni** [spark/particle-dev-local-compiler#19]
Was doing some debugging today and cross-compared compiler errors on the DEV IDE vs the BUILD IDE and they are not the same.

The DEV IDE did not give back the same level of resolution on warnings and errors as the BUILD IDE did. 

Is there any way we can have the same compiler errors/warnings ?

**Comment by suda** [comment]
Is this related to local compiler or maybe whole [Particle Dev](https://github.com/spark/spark-dev/issues)? Local compiler shows all errors in console (similarly to Build IDE).

**Comment by chobberoni** [comment]
@suda I'm referencing the compiler that is behind Particle Dev (https://www.particle.io/dev)

**Comment by suda** [comment]
Ah! So we're discussing in wrong repo 😄(easy to get confused as there are a lot of repos that makes Particle Dev).

There are multiple issues opened ([#79](https://github.com/spark/spark-dev/issues/79), [#77](https://github.com/spark/spark-dev/issues/77), [#123](https://github.com/spark/spark-dev/issues/123)) which should bring Dev closer to Build in terms of showing errors.
