### ISSUE TITLE
Particle Dev crash @ firmware update of local compiler

### ISSUE THREAD

**Issue by rafaelmaeuer** [spark/particle-dev-local-compiler#20]
same issue as here: 
https://github.com/atom/atom/issues/9734
Windows 10 x64
ATOM 1.0.19
any help?
![crash](https://cloud.githubusercontent.com/assets/6418459/11610325/c40d2ffa-9b9f-11e5-8141-abb16a01d56a.JPG)

**Comment by suda** [comment]
What's the Atom version?

**Comment by rafaelmaeuer** [comment]
As I wrote above ATOM 1.0.19:
![atom](https://cloud.githubusercontent.com/assets/6418459/11640559/73c0eb00-9d33-11e5-8279-c2b3ae24bacd.JPG)

**Comment by suda** [comment]
Ah, didn't saw it the first time. Could you try updating Atom to latest version?

**Comment by rafaelmaeuer** [comment]
This doesn't work, it says "No update available". If i manually install atom and replace the source in the Particle Dev directory, only atom is left after restart.
![update](https://cloud.githubusercontent.com/assets/6418459/11642635/54df1728-9d3f-11e5-879d-71273553dfc5.JPG)

**Comment by Zuph** [comment]
Same issue here. Same versions of Atom, Windows, etc.

**Comment by suda** [comment]
This is due to old Atom version budled with Particle Dev. Until we update it you could try installing [standalone Atom](https://atom.io/) and all dependent packages.
