### ISSUE TITLE
server error - invalid mode "/input"

### ISSUE THREAD

**Issue by ghost** [spark/particle-dev-local-compiler#24]
Hello,
my name is Joel .
I wonder why when I do the local compilation me these errors appear :

![1](https://cloud.githubusercontent.com/assets/9480073/14046794/8afc5f6c-f29b-11e5-9468-745242cdbe63.png)
![2](https://cloud.githubusercontent.com/assets/9480073/14046793/8afb325e-f29b-11e5-937f-10547fabe2c1.png)
![3](https://cloud.githubusercontent.com/assets/9480073/14046795/8b00306a-f29b-11e5-8ed3-b00d53d15d1b.png)

**Comment by suda** [comment]
@mjoelmendes what version of Docker are you running?

**Comment by ghost** [comment]
DockerToolbox-1.10.3

**Comment by suda** [comment]
Could you restart the vm? (`docker-machine stop default && docker-machine start default`)
Also could you paste results of `docker images` command?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14140867/6b432170-f673-11e5-87fd-5842e17d025b.png)

**Comment by mjoelmendes** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14140999/45029eae-f674-11e5-9d60-9c6e7ca15285.png)

**Comment by suda** [comment]
Did it help? Also can you share the `docker images` too?

**Comment by mjoelmendes** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14173340/352420f4-f735-11e5-908e-2480f199a990.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14173347/3c585a3e-f735-11e5-8425-67a4a9df1fc8.png)

**Comment by suda** [comment]
Ok, it looks like you have only `latest` version (which isn't recommended to use and [won't be available](#1) in next release). You can try following:

```
docker rmi particle/buildpack-particle-firmware:latest
docker pull particle/buildpack-particle-firmware:v0.4.9-rc.3
```

Then restart Atom and see if it helped.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14173729/b2e01bc2-f737-11e5-965e-000e1558fd4a.png)

**Comment by suda** [comment]
There are some containers still using the `latest` tag. Try doing `docker ps -a` and then `docker rm <CONTAINER_ID>` for each one using `latest` tag.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14174263/30a1118a-f73b-11e5-936c-43bc62e1601b.png)

![image](https://cloud.githubusercontent.com/assets/9480073/14174249/2660a672-f73b-11e5-96fe-288f27d470ed.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14174288/5e5ae8e4-f73b-11e5-8814-65c2834e49e9.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/9480073/14174361/c2a526ca-f73b-11e5-8667-1aef018182db.png)

**Comment by suda** [comment]
If you click **v0.4.9-rc.3** and select it again, the compile should succeed.

You could also increase timeout in package settings.

**Comment by ghost** [comment]
How do I increase the waiting time for package settings ??

**Comment by suda** [comment]
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> -> Settings View: View Installed Packages -> Search for `local-compiler` -> Click `Settings` -> Adjust `Compile Timeout` value

**Comment by ghost** [comment]
I'm sorry , but I have done everything you told me , and continues to make the same mistake

![image](https://cloud.githubusercontent.com/assets/9480073/14175299/141a632a-f742-11e5-8ab5-f8aea50106d4.png)

![image](https://cloud.githubusercontent.com/assets/9480073/14175312/24b63f7e-f742-11e5-85b9-d9d2bfc96d48.png)

![image](https://cloud.githubusercontent.com/assets/9480073/14175369/83782dec-f742-11e5-91f7-a3c3946de3cf.png)

**Comment by ghost** [comment]
already I restarted the PC and all, but still .
I could give access to my pc if you need

**Comment by suda** [comment]
Can you ping me at: wojtek [at] particle [dot] io?

**Comment by ghost** [comment]
I'm sorry , but not QI received what you mean :
Can you ping me at: wojtek [ at] particle [dot ] io ?

**Comment by suda** [comment]
I meant if you can email me: wojtek@particle.io :)

**Comment by ghost** [comment]
already sent you

**Comment by ghost** [comment]
:D

**Comment by suda** [comment]
Wow, that's a weird one. When mounting volume in Docker it's specified in `LOCAL_DIR:CONTAINER_DIR:MODE` format. But because Windows path contains `:` it parses it wrong, thinking that `/input` is mode... So possible fix would be escaping `:`.

It looks like you need to use cloud compilation until this issue is fixed.

**Comment by ghost** [comment]
ok , I'll wait , can not tell me if it will take ??
