### ISSUE TITLE
doesn't appear to work with Electron

### ISSUE THREAD

**Issue by nanodust** [spark/particle-dev-local-compiler#25]
I'm possibly having Docker issues (tho docker works fine on my system generally)
even so, none of the menus read 'electron' - 
and there's been no commit to repo since the electron's release.

so I'm writing for a Y/N as to whether or not we should expect local compilation to work with the Electron.

**Comment by suda** [comment]
That is correct. We have to add support for Electron. Current sprint is focused on improving Build IDE but next one should take care of Dev issues (including this one).

**Comment by csoulakian** [comment]
This should be included in the README. I spent a long time trying to get this plugin to work only to find out it won't work with the Electron.

**Comment by mfogel** [comment]
A whitelist of supported platforms should be added to the README. As this package exists, this is essentially a booby trap for people working on the electron...

**Comment by nanodust** [comment]
lack of local compiler made me not want to work on the platform. I've not touched it since this. 

Is there now a local compiler that works with the electron?

**Comment by suda** [comment]
Yep, should work with all our platforms that include: Core, Photon, P1 and Electron!

**Comment by nanodust** [comment]
nice ! i'll dust it off and try again!
