### ISSUE TITLE
Docker Error HTTP Code 400

### ISSUE THREAD

**Issue by unseenshadow2** [spark/particle-dev-local-compiler#27]
Here is the error given by Particle Dev when trying to run a local compile:
`Error: (HTTP code 400) unexpected - starting container with HostConfig was deprecated since v1.10 and removed in v1.12`

This is on a Windows install and this error appeared immediately after attempting to run the first compilation on the machine. Docker is running.
![particle-dev-compile-issue](https://cloud.githubusercontent.com/assets/12752570/20579814/2298c4be-b18c-11e6-94a4-520fd63667e0.PNG)

[Other using having the same issue.](https://community.particle.io/t/particle-dev-local-compiler-error-http-code-400-unexpected-starting-container-with-hostconfig-was-deprecated-since-v1-10-and-removed-in-v1-12/25572)

**Comment by suda** [comment]
Thanks for the report! This package is slightly outdated and we hope to give it an update in Q1 2017.
