### ISSUE TITLE
Particle Dev.app includes an incompatible release of node

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev-local-compiler#31]
Installation of `particle-dev-local-compiler-0.1.0` fails due to node version mismanagement, on macOS 10.12.4.

> npm WARN engine sb-exec@3.1.0: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
> npm WARN engine strip-bom-buf@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
> npm ERR! Darwin 16.5.0
> npm ERR! argv "/Applications/IDE/Particle Dev.app/Contents/Resources/app/apm/bin/node" "/Applications/IDE/Particle Dev.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ReiVilo/.particledev/.apm/.apmrc" "--userconfig" "/Users/ReiVilo/.particledev/.apmrc" "install" "/private/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/d-11749-60287-1780dmk/package.tgz" "--target=0.36.8" "--arch=x64"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ENOTSUP
> 
> npm ERR! notsup Unsupported
> npm ERR! notsup Not compatible with your version of node/npm: docker-compose-tool@0.0.1
> npm ERR! notsup Required: {"node":">= 6.2"}
> npm ERR! notsup Actual:   {"npm":"2.13.3","node":"0.10.40"}
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /private/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/apm-install-dir-11749-60287-jp6u3t/npm-debug.log

while

`$ node -v
v6.9.1
`

**Comment by rei-vilo** [comment]
`node`provided with `Particle Dev.app` is too old!

`
$ /Applications/IDE/Particle\ Dev.app/Contents/Resources/app/apm/bin/node -v
v0.10.40
`

**Comment by rei-vilo** [comment]
Replacing `/Applications/IDE/Particle\ Dev.app/Contents/Resources/app/apm/bin/node` with `node` release 6.9.1 fails due to

> $ node --harmony_collections
> node: bad option: --harmony_collections

**Comment by suda** [comment]
Yes, [we'll update Particle Dev App](https://github.com/spark/particle-dev-local-compiler/issues/30#issuecomment-299450584) this week. Until then this package can be tested in latest Atom

**Comment by rei-vilo** [comment]
I'm already using the latest release of Atom.

<img width="420" alt="capture 2017-05-10 a 12 57 41" src="https://cloud.githubusercontent.com/assets/951776/25895475/4dd0e7d8-3580-11e7-9bce-033bd2c73a1a.png">

I don't understand the difference between the latest Atom IDE and the available Particle Dev IDE for managing extensions.

**Comment by rei-vilo** [comment]
Related to #30

**Comment by suda** [comment]
Oh sorry, let me explain:
Particle Dev consists of multiple Atom packages. They can be installed in [Atom itself](https://atom.io/) and this is how we ship the latest, beta packages. 

[Particle Dev App](https://github.com/spark/particle-dev-app) is a standalone version of Atom that bundles with all those packages to make the installation easier.

**Comment by rei-vilo** [comment]
Ok, thanks!

I'll wait for the new release of Particle Dev, as my installation of Atom is already used with another set of packages.

**Comment by rei-vilo** [comment]
Any update? Thank you!

**Comment by suda** [comment]
Just an update, we updated the Particle Dev App to 1.18.0 which bundles new Node :)
