### ISSUE TITLE
Platform 'core' does not support dynamic modules

### ISSUE THREAD

**Issue by robertdxyz** [spark/particle-dev-local-compiler#4]
I am trying to compile `Blink an LED` example for `Core` with firmware `0.4.5`. The console output is empty and in `run.log` is this:

```
processing  /workspace/build
processing  /workspace/core_firmware_1447171963844.bin
processing  /workspace/relay.ino
makefile:30: *** "Platform 'core' does not support dynamic modules".  Stop.
arm-none-eabi-size: '/workspace/target/workspace.elf': No such file
Finished in: 0.156344 seconds
```

The online compilation works.

**Comment by suda** [comment]
`0.4.5` didn't support dynamic modules on Core. They do work from `0.4.6` and above.

**Comment by robertdxyz** [comment]
Thanks

**Comment by robertdxyz** [comment]
When using `0.4.6` with `Core` I get an empty bin file and this:

```
processing  /workspace/build
processing  /workspace/relay.ino
../build/module-defaults.mk:95: *** Recursive variable 'TARGET_PATH' references itself (eventually).  Stop.
arm-none-eabi-size: '/workspace/target/workspace.elf': No such file
Finished in: 0.109069 seconds
```

With `0.4.7` with `Core` I get a timeout as state in #6.

`Photon` works with all versions.

**Comment by rei-vilo** [comment]
How to get SDK 0.4.7? I'm stuck at 0.4.6.

**Comment by suda** [comment]
@rei-vilo when you click version in status bar, what are the versions available?

**Comment by rei-vilo** [comment]
Here's the list:

<img width="320" alt="capture 2015-11-11 a 12 36 49" src="https://cloud.githubusercontent.com/assets/951776/11090282/044a602a-8871-11e5-9ae9-9e01709f92cd.png">

**Comment by suda** [comment]
Updating firmware versions should help (it's possible this was interrupted).

**Comment by rei-vilo** [comment]
I've just another Update firmware. After a while, the blue window closes down but the higher release is still 0.4.6.

![capture 2015-11-11 a 14 21 12](https://cloud.githubusercontent.com/assets/951776/11091968/d78db2c6-887f-11e5-8368-69656b5e6eea.png)

<img width="181" alt="capture 2015-11-11 a 14 21 36" src="https://cloud.githubusercontent.com/assets/951776/11091969/dc043de8-887f-11e5-9258-1f9ea10dade1.png">

**Comment by suda** [comment]
Hmmm, you could try fetching it manually:

```
$ eval "$(docker-machine env default)"
$ docker pull particle/buildpack-particle-firmware:v0.4.7
```

**Comment by rei-vilo** [comment]
Thanks. It worked. Version 0.4.7 now appears on the SDK list.

Maybe the explanation relies on `Status: Image is up to date for particle/buildpack-particle-firmware:v0.4.7
docker.io/particle/buildpack-particle-firmware: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
`

> $ eval "$(docker-machine env default)"
> 
> $ docker pull particle/buildpack-particle-firmware:v0.4.7
> 
> Pulling repository docker.io/particle/buildpack-particle-firmware
> c0952bcd5e9f: Pulling image (v0.4.7) from docker.io/particle/buildpack-particle-c0952bcd5e9f: Pulling image (v0.4.7) from docker.io/particle/buildpack-particle-c0952bcd5e9f: Pulling dependent layers 
> 9231a146a3b3: Download complete 
> 616b550dc233: Download complete 
> dd59d9976e39: Download complete 
> 4e9c8310e711: Download complete 
> d3e35e295f5a: Download complete 
> cb66a35248bd: Download complete 
> 5e51ae26e36e: Download complete 
> c0952bcd5e9f: Download complete 
> 2ae08e6d636f: Download complete 
> 1720e08000f7: Download complete 
> 9580ae5c5930: Download complete 
> 64197d4b059e: Download complete 
> 4fc146c21cd9: Download complete 
> 91e69a92a1e7: Download complete 
> 519260a74a05: Download complete 
> 006241fcd363: Download complete 
> 69397a71cf15: Download complete 
> 01fbb55846b7: Download complete 
> c0aaffe944bb: Download complete 
> 3156e0125a09: Download complete 
> 1c589c389860: Download complete 
> 645d9fffc21e: Download complete 
> 20dc053acd82: Download complete 
> e2d4aeae8cdf: Download complete 
> ca2805321503: Download complete 
> 83c428323ddc: Download complete 
> 9ec834951d5b: Download complete 
> 4ef6cee612cd: Download complete 
> 9c61160f3a90: Download complete 
> 9390bfddec22: Download complete 
> Status: Image is up to date for particle/buildpack-particle-firmware:v0.4.7
> docker.io/particle/buildpack-particle-firmware: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

**Comment by rei-vilo** [comment]
SDK 0.4.7 not supported because it fails agains Core as per #6?

**Comment by mikey0000** [comment]
`makefile:20: *** "Platform 'core' does not support dynamic modules".  Stop.` still failing on latest branch

**Comment by suda** [comment]
We're reworking the Docker buildpacks so until we finish this may persist.
