### ISSUE TITLE
Compilation timed out

### ISSUE THREAD

**Issue by robertdxyz** [spark/particle-dev-local-compiler#6]
Program: Blink an LED
Firmware: v0.4.7
Board: Core

The compilation works witg `v0.4.6`. It also works with `v0.4.7` if I compile for `Photon` instead of `Core`

Log files for timeout compilation:

`run.log`

```
processing  /workspace/build
processing  /workspace/core_firmware_1447174998474.bin
processing  /workspace/photon_firmware_1447175030448.bin
processing  /workspace/photon_firmware_1447175037772.bin
processing  /workspace/relay.ino
make -C ../user 
make[1]: Entering directory '/firmware/user'
Building file: /workspace/relay.cpp
Invoking: ARM GCC CPP Compiler
mkdir -p ../build/target/user/platform-0-lto/workspace/
arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DSPARK_PLATFORM -DFLASHEE_EEPROM -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -I./inc -I../wiring/inc -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I/workspace/ -I./libraries -I. -MD -MP -MF ../build/target/user/platform-0-lto/workspace/relay.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DSPARK_PLATFORM_NET=CC3000 -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc  -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto -std=gnu++11  -fno-exceptions -fno-rtti -fcheck-new -c -o ../build/target/user/platform-0-lto/workspace/relay.o /workspace/relay.cpp

Building target: ../build/target/user/platform-0-lto/workspace/libuser.a
Invoking: ARM GCC Archiver
mkdir -p ../build/target/user/platform-0-lto/workspace/
arm-none-eabi-ar -cr ../build/target/user/platform-0-lto/workspace/libuser.a ../build/target/user/platform-0-lto/workspace/relay.o

make[1]: Leaving directory '/firmware/user'
make -C ../wiring 
make[1]: Entering directory '/firmware/wiring'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/wiring'
make -C ../hal 
make[1]: Entering directory '/firmware/hal'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/hal'
make -C ../system 
make[1]: Entering directory '/firmware/system'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/system'
make -C ../services 
make[1]: Entering directory '/firmware/services'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/services'
make -C ../communication 
make[1]: Entering directory '/firmware/communication'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/communication'
make -C ../platform 
make[1]: Entering directory '/firmware/platform'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/platform'
make -C ../wiring_globals 
make[1]: Entering directory '/firmware/wiring_globals'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/firmware/wiring_globals'
Building file: src/module_info.c
Invoking: ARM GCC C Compiler
mkdir -p /workspace/target/obj/./src/
arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -Werror -I../user/inc -I../wiring/inc -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I. -MD -MP -MF /workspace/target/obj/./src/module_info.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto -Wno-pointer-sign -std=gnu99  -c -o /workspace/target/obj/./src/module_info.o src/module_info.c

Building file: ../build/arm/startup/startup_stm32f10x_md.S
Invoking: ARM GCC Assembler
mkdir -p /workspace/target/obj/startup/
arm-none-eabi-gcc -I../build/arm/startup -Wa,--defsym -Wa,SPARK_INIT_STARTUP=1 -x assembler-with-cpp -fmessage-length=0 -g3 -gdwarf-2 -mcpu=cortex-m3 -mthumb -c -o /workspace/target/obj/startup/startup_stm32f10x_md.o ../build/arm/startup/startup_stm32f10x_md.S

Building target: /workspace/target/workspace.elf
Invoking: ARM GCC C++ Linker
mkdir -p /workspace/target/
arm-none-eabi-g++ -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -Werror -I../user/inc -I../wiring/inc -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I. -MD -MP -MF /workspace/target/workspace.elf.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto /workspace/target/obj/./src/module_info.o  /workspace/target/obj/startup/startup_stm32f10x_md.o --output /workspace/target/workspace.elf -Tlinker_stm32f10x_md_dfu.ld -L../build/arm/linker --specs=nano.specs -lc -lnosys -u _printf_float -Wl,-Map,/workspace/target/workspace.map  -L../build/target/user/platform-0-lto/workspace/ -L../build/target/wiring/platform-0-lto/ -L../build/target/system/platform-0-lto/ -L../build/target/services/platform-0-lto/ -L../build/target/communication/platform-0-lto-prod-0/ -L../build/target/hal/platform-0-lto/ -L../build/target/platform/platform-0-lto/ -L../build/target/wiring_globals/platform-0-lto/ -L../build/arm/linker -Wl,--whole-archive -luser -lwiring -lhal -lsystem -lservices -lcommunication -lplatform -lwiring_globals -Wl,--no-whole-archive -nostartfiles -Xlinker --gc-sections -flto -Os -fuse-linker-plugin

Invoking: ARM GNU Create Flash Image
arm-none-eabi-objcopy -O binary /workspace/target/workspace.elf /workspace/target/workspace.bin.pre_crc
if [ -s /workspace/target/workspace.bin.pre_crc ]; then \
head -c $((`stat -c %s /workspace/target/workspace.bin.pre_crc` - 38)) /workspace/target/workspace.bin.pre_crc > /workspace/target/workspace.bin.no_crc && \
tail -c 38 /workspace/target/workspace.bin.pre_crc > /workspace/target/workspace.bin.crc_block && \
test "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20280078563412" = `xxd -p -c 500 /workspace/target/workspace.bin.crc_block` && \
shasum -a 256 /workspace/target/workspace.bin.no_crc | cut -c 1-65 | xxd -r -p | dd bs=1 of=/workspace/target/workspace.bin.pre_crc seek=$((`stat -c %s /workspace/target/workspace.bin.pre_crc` - 38)) conv=notrunc  && \
head -c $((`stat -c %s /workspace/target/workspace.bin.pre_crc` - 4)) /workspace/target/workspace.bin.pre_crc > /workspace/target/workspace.bin.no_crc && \
 crc32 /workspace/target/workspace.bin.no_crc | cut -c 1-10 | xxd -r -p | dd bs=1 of=/workspace/target/workspace.bin.pre_crc seek=$((`stat -c %s /workspace/target/workspace.bin.pre_crc` - 4)) conv=notrunc ;\
fi
32+0 records in
32+0 records out
32 bytes (32 B) copied, 0.0185691 s, 1.7 kB/s
4+0 records in
4+0 records out
4 bytes (4 B) copied, 0.0517712 s, 0.1 kB/s
[ ! -f /workspace/target/workspace.bin ] || rm /workspace/target/workspace.bin
mv /workspace/target/workspace.bin.pre_crc /workspace/target/workspace.bin

arm-none-eabi-objcopy -O ihex /workspace/target/workspace.elf /workspace/target/workspace.hex
arm-none-eabi-size --format=berkeley /workspace/target/workspace.elf
   text    data     bss     dec     hex filename
  77036    1040    8564   86640   15270 /workspace/target/workspace.elf
arm-none-eabi-objdump -h -S /workspace/target/workspace.elf > /workspace/target/workspace.lst

```

`stderr.log`

```
32+0 records in
32+0 records out
32 bytes (32 B) copied, 0.0185691 s, 1.7 kB/s
4+0 records in
4+0 records out
4 bytes (4 B) copied, 0.0517712 s, 0.1 kB/s

```

**Comment by rei-vilo** [comment]
Same for me. 

Local compilation with 0.4.6 runs fine against Core but fails against Photon.

**Comment by rei-vilo** [comment]
After a fresh re-boot of my Mac, compilation with SDK 0.4.6 succeeds for both Core and Particle.

I was prompted to update VBox to `VirtualBox-5.0.10-104061-OSX`.

**Comment by rei-vilo** [comment]
While **SDK 0.4.6** succeeds against both Core and Photon, **SDK 0.4.7** only succeeds against Photon and fails against Core with `Compilation timed out` error message.
- run.log

> processing  /workspace/.DS_Store
> processing  /workspace/BlinkPhoton.cpp
> processing  /workspace/build
> make -C ../user 
> make[1]: Entering directory '/firmware/user'
> Building file: /workspace/BlinkPhoton.cpp
> Invoking: ARM GCC CPP Compiler
> mkdir -p ../build/target/user/platform-0-lto/workspace/
> arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DSPARK_PLATFORM -DFLASHEE_EEPROM -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -I./inc -I../wiring/inc -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I/workspace/ -I./libraries -I. -MD -MP -MF ../build/target/user/platform-0-lto/workspace/BlinkPhoton.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DSPARK_PLATFORM_NET=CC3000 -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc  -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto -std=gnu++11  -fno-exceptions -fno-rtti -fcheck-new -c -o ../build/target/user/platform-0-lto/workspace/BlinkPhoton.o /workspace/BlinkPhoton.cpp
> 
> Building target: ../build/target/user/platform-0-lto/workspace/libuser.a
> Invoking: ARM GCC Archiver
> mkdir -p ../build/target/user/platform-0-lto/workspace/
> arm-none-eabi-ar -cr ../build/target/user/platform-0-lto/workspace/libuser.a ../build/target/user/platform-0-lto/workspace/BlinkPhoton.o
> 
> make[1]: Leaving directory '/firmware/user'
> make -C ../wiring 
> make[1]: Entering directory '/firmware/wiring'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/wiring'
> make -C ../hal 
> make[1]: Entering directory '/firmware/hal'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/hal'
> make -C ../system 
> make[1]: Entering directory '/firmware/system'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/system'
> make -C ../services 
> make[1]: Entering directory '/firmware/services'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/services'
> make -C ../communication 
> make[1]: Entering directory '/firmware/communication'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/communication'
> make -C ../platform 
> make[1]: Entering directory '/firmware/platform'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/platform'
> make -C ../wiring_globals 
> make[1]: Entering directory '/firmware/wiring_globals'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/firmware/wiring_globals'
> Building file: src/module_info.c
> Invoking: ARM GCC C Compiler
> mkdir -p /workspace/target/obj/./src/
> arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -Werror -I../user/inc -I../wiring/inc -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I. -MD -MP -MF /workspace/target/obj/./src/module_info.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto -Wno-pointer-sign -std=gnu99  -c -o /workspace/target/obj/./src/module_info.o src/module_info.c
> 
> Building file: ../build/arm/startup/startup_stm32f10x_md.S
> Invoking: ARM GCC Assembler
> mkdir -p /workspace/target/obj/startup/
> arm-none-eabi-gcc -I../build/arm/startup -Wa,--defsym -Wa,SPARK_INIT_STARTUP=1 -x assembler-with-cpp -fmessage-length=0 -g3 -gdwarf-2 -mcpu=cortex-m3 -mthumb -c -o /workspace/target/obj/startup/startup_stm32f10x_md.o ../build/arm/startup/startup_stm32f10x_md.S
> 
> Building target: /workspace/target/workspace.elf
> Invoking: ARM GCC C++ Linker
> mkdir -p /workspace/target/
> arm-none-eabi-g++ -DSTM32_DEVICE -DSTM32F10X_MD -DPLATFORM_THREADING=0 -DPLATFORM_ID=0 -DPLATFORM_NAME=core -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=0 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.7 -DRELEASE_BUILD -Werror -I../user/inc -I../wiring/inc -I../hal/inc -I../hal/shared -I../hal/src/core -I../hal/src/stm32 -I../system/inc -I../services/inc -I../communication/src -I../communication/lib/tropicssl/include -I../platform/shared/inc -I../platform/MCU/STM32F1xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F1xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F1xx/CMSIS/Include -I../platform/MCU/STM32F1xx/CMSIS/Device/ST/Include -I../platform/NET/CC3000/CC3000_Host_Driver -I../dynalib/inc -I. -MD -MP -MF /workspace/target/workspace.elf.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -flto /workspace/target/obj/./src/module_info.o  /workspace/target/obj/startup/startup_stm32f10x_md.o --output /workspace/target/workspace.elf -Tlinker_stm32f10x_md_dfu.ld -L../build/arm/linker --specs=nano.specs -lc -lnosys -u _printf_float -Wl,-Map,/workspace/target/workspace.map  -L../build/target/user/platform-0-lto/workspace/ -L../build/target/wiring/platform-0-lto/ -L../build/target/system/platform-0-lto/ -L../build/target/services/platform-0-lto/ -L../build/target/communication/platform-0-lto-prod-0/ -L../build/target/hal/platform-0-lto/ -L../build/target/platform/platform-0-lto/ -L../build/target/wiring_globals/platform-0-lto/ -L../build/arm/linker -Wl,--whole-archive -luser -lwiring -lhal -lsystem -lservices -lcommunication -lplatform -lwiring_globals -Wl,--no-whole-archive -nostartfiles -Xlinker --gc-sections -flto -Os -fuse-linker-plugin
- stderr.log

Empty!

**Comment by robertdxyz** [comment]
I tried again with `Core` and firmware `v0.4.7` and it succeded after a few tries.
Sometimes it gives this error:

```
Error: HTTP code is 500 which indicates error: server error - Cannot kill container a15a0c73ced6b3dd3e5fc43d485ed8fd6ef179de3638058b8c3c7678a0bffa83: Container a15a0c73ced6b3dd3e5fc43d485ed8fd6ef179de3638058b8c3c7678a0bffa83 is not running
```

But it worked only once. Timeout now :)

**Comment by suda** [comment]
Will have a look at that

**Comment by ghost** [comment]
Error: HTTP code is 500 which indicates error: server error - Cannot kill container a15a0c73ced6b3dd3e5fc43d485ed8fd6ef179de3638058b8c3c7678a0bffa83: Container a15a0c73ced6b3dd3e5fc43d485ed8fd6ef179de3638058b8c3c7678a0bffa83 is not running

Here is solution?? 

![image](https://cloud.githubusercontent.com/assets/9480073/14054690/2bd3cb32-f2d3-11e5-88dc-ab9d1b05f692.png)
